spring:
  profiles:
    active: default
    default: default
  datasource:
    url: jdbc:postgresql://13.209.228.191:5432/testtable
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 500
        format_sql: false
        show-sql: false
    defer-datasource-initialization: true
    database: postgresql